ara-software/AraProc

- araproc/analysis/snr.py
SNR calculation now excludes channels rather than includes them.
> Updated SNR to exclude channels

- araproc/analysis/interferometry.py
- araproc/analysis/standard_reco.py
- araproc/framework/config_files/analysis_configs.yaml
- araproc/framework/constants.py
- araproc/framework/dataset.py
- araproc/framework/waveform_utilities.py
Removed support for stationId 1 and added support for stationId 100. Added a global constants file for future use going forward.
> A1 stationId fix

- araproc/analysis/snr.py
Added support for np.ndarrays to be passed to snr functions rather than just TGraphs.
> Add support for np.ndarrays for snr functions.

- araproc/analysis/rpr.py
- araproc/analysis/standard_reco.py
- examples/test_rpr.py
> Adding first version of RPR Calculation

- araproc/analysis/impulsivity.py
- araproc/analysis/impulsivity_and_matrices.py
- araproc/framework/config_files/analysis_configs.yaml
I did simple check for RF and CP like events . I find it okay. I have still kept the plotting script within the script hoping that it will help folks to debug this function. The results I saw are here :
> Impulsivity related metrices

- araproc/analysis/standard_reco.py
- araproc/framework/data_visualization.py
- araproc/framework/dataset.py
The AraRoot RayTraceCorrelator got major speed upgrades. This adapts AraProc to those updates.
> Use the updated RTC in AraRoot

- araproc/analysis/impulsivity.py
Added calculation of significance of erf-linear fit to cdf curve over linear fit using Wilks' theorem.
> Added significance calculation to impulsivity.

- araproc/analysis/standard_reco.py
I forgot to push my local branch to GitHub before merging the PR. This corrects for that.
> Merge last couple changes from original CSW PR

- araproc/analysis/daq_quality_cut.py
Add funcitonality to support ARA05's force trigger readout from the Phased Array while performing the DAQ quality cut
> Add Force Trigger Trigger Type for Station 5

- araproc/analysis/impulsivity.py
For some reason scipy's `curve_fit` was throwing an error when fitting the `erf_linear` to cdf data with parameter bounds. This seems to be something to do with the data type or memory limitations during SVD? But we aren't really sure. For posterity the error is copied below.
Since I could not find the problem and there doesn't seem to be any obvious issues with the data itself, I've reimplemented the curve fitting using ROOT. This seems to be working. 
```
Traceback (most recent call last):
File "/home/mmuzio/FiveStation/scripts/L2/L2.py", line 173, in <module>
this_imp_results_v = impulsivity.calculate_impulsivity_measures(this_csw_volts_v, this_csw_times_v)
File "/home/mmuzio/AraProc/araproc/analysis/impulsivity.py", line 113, in calculate_impulsivity_measures
popt, _ = …
```
> Impulsivity curve fit reimplementation

- araproc/analysis/standard_reco.py
Removed some try/except blocks, save more information to the `reco_results` object, and cleaned some bugs/typos in CSW.
> Update Standard Reco

- araproc/analysis/standard_reco.py
Accounted for the fact that the max correlation can be above the ice surface by removing the `z_thresh` condition. Fixed the calculation across maps to use the maximum correlation value across all maps as the reference value. Fixed the A1 calpulser radius.
> Fixed min depth corr calculation.

- araproc/analysis/standard_reco.py
Rounding wasn't working, removed rounding and reformatted trimming block that's a bit more flexible
> Fix CSW Trimming

- araproc/framework/data_visualization.py
Forced skymap colorbar to always start at 0.
> Unsuppress skymap colorbar 0

- examples/process_run.py
- examples/test_rpr.py
Here is a quick fix in existing examples .
> fix broken examples, it was calling function get_waveforms which was  renamed to get_wavepacket in dataset.py file

- araproc/analysis/standard_reco.py
Add comments to areas where the CSW's warning tracker is incremented. Reworked the CSW warning values as I realized I planned them poorly (not incorrectly, but not intuitively) before.
> CSW Warning Updates

- araproc/framework/dataset.py
Fixed file existence check when loading from cvmfs. @Mohammad-Neutrino confirmed this works.
> Fixed cvmfs ped file check.

- araproc/framework/dataset.py
> Update pedestal paths to v2

- araproc/analysis/standard_reco.py
- araproc/framework/constants.py
- araproc/framework/data_visualization.py
- araproc/framework/map_utilities.py
> First version of the addition of landmarks in AraProc

- araproc/analysis/standard_reco.py
- araproc/framework/constants.py
- araproc/framework/data_visualization.py
- araproc/framework/map_utilities.py
This PR adds functionality to calculate the elevation angle of a signal by comparing the time differences between signals on a single string assuming a plane wave approximation. A combined elevation angle from all pairs is calculated by minimizing the error between each pair's reconstruction.
Also updated the skymap plotting to be able to include this and cleaned up some code.
> Pair-wise plane wave reconstruction

- araproc/framework/dataset.py
- araproc/framework/file_utilities.py
- araproc/framework/housekeeping.py
- examples/hk_example.py
This makes AraProc able to read hk file and daq config files.
> Housekeeping

- araproc/analysis/standard_reco.py
- araproc/framework/file_utilities.py
Changed directories for timing tables and pedestals to a (hopefully) temporary location while stashcache is sorted out.
> Switched data file directories to temporary space.

- araproc/framework/housekeeping.py
catch cases where the cp file exists but is empty for some reason
> catch cases where the cp file exists but is empty for some reason

- araproc/analysis/snr.py
Added a simple function to calculate the channel-average rms.
> Average rms

- araproc/framework/file_utilities.py
Added helper function to parse the run number from a ROOT file directly.
> Added run number parser

- araproc/__init__.py
- araproc/analysis/__init__.py
- araproc/analysis/standard_reco.py
Since the Ray Trace timing tables need to be flexible I made the path to the ray tracing tables yet another environment variable required for the analysis.
> Make ray tracing tables an environment variable

- araproc/framework/dataset.py
Fixed small bug in the assignment of that bandpassed-only waveform.
> Ensure that bandpassed trace is properly assigned.

- araproc/framework/config_files/analysis_configs.yaml
This adds the CW filters for A5.
> A5 filters

- araproc/framework/config_files/analysis_configs.yaml
> Correcting my silly mistake!

- araproc/framework/config_files/analysis_configs.yaml
Remaining filters for A3. Some of the filters are pretty harsh, but I did need them to eliminate some clear spikes in the spectra. I can add before and after pictures if people want to see.
> A3 filters for C5-9

- araproc/__init__.py
- araproc/framework/dataset.py
The direction saved is the one directly from AraSim. 
The XY position is a rough translation from AraSim and may not preserve the ice flow coordinates. @AlanSalcedo I'd love your input on this if you have the time. I wasn't sure if station.GetX() - event.GetX() was a valid calculation. 
The depth uses the FlatToEarth_SameAngle conversion from the AraSim retracer.
> Add event vertex and direction to simulation information object

- araproc/framework/config_files/analysis_configs.yaml
This adds some filters for high peaks at low frequencies and adjusts some at higher frequencies. Overall the filters are pretty unchanged though.
> A2 filters

- araproc/framework/config_files/analysis_configs.yaml
Changes to adjust the new CW filtering techniques
> Changes in A4 filters

- araproc/framework/config_files/analysis_configs.yaml
Added in some filters for C1. These largely look the same as the ones for C2.
> A5 C1 Filters

- araproc/framework/config_files/analysis_configs.yaml
I might need a few more hours to make changes to config 3, but I will try to do it as soon as possible.
> A1 Config 1 and 2 updates

- araproc/framework/file_utilities.py
This sensor hk file utility finder needs to search for A1, not A100.
> swap in the A1 when grepping around for sensor hk

- araproc/framework/config_files/analysis_configs.yaml
Cleans up CW but doesn't kill localized sources.
> Updated A5C1 filters.

- araproc/framework/dataset.py
For noise and neutrino simulations its usually "[station][config]000[merged_file_number (zfill 4)]" and for effective volume simulations its usually "[station][config][lgE * 10][merged_file_number (zfill 4)]"
> Create run numbers for simulation L2

- araproc/framework/file_utilities.py
> split hk file finder utility

- araproc/framework/config_files/analysis_configs.yaml
The new config will appear to split config 7 into two so it has the same channels masked.
> Add new A2 config

- araproc/analysis/standard_reco.py
This introduces the pair-weighting by SNR to standard reco.
> add the ability to snr weight via argument
