- araproc/__init__.py
- araproc/analysis/standard_reco.py
- examples/run_example.py
This adds a small helper function to `araproc.analysis.standard_reco` to lookup the arrival time at an antenna from the ray trace correlator table.
> Add timing lookup

- araproc/analysis/standard_reco.py
There was a minor A1 stationID issue in _standard_reco.py_ while loading timing tables using _calpulser_r_library_
> fixing a small A1 stationID bug

- araproc/analysis/standard_reco.py
- araproc/framework/map_utilities.py
This function calculates the minimum correlation fraction depth:
You can specify (1) a fraction of the peak correlation -default 60%- and (2) a threshold depth where the surface "starts" or "it's reached" - neg 10 m- by default. 
This function starts a 'min_depth' from a neg. infinity depth and replaces 'min_depth' when it finds a new depth (measured from the surface and not above the surface) with a correlation => max_corr * fraction.
> Minimum correlation fraction depth

- araproc/analysis/standard_reco.py
- araproc/framework/dataset.py
- examples/run_example.py
This pull request is aimed at helping merge the csw and corr_snr functions into standard_reco.
Cached correlation functions in `StandardReco` object as private variables. Added a private getter function for correlation functions and a public function to look up index of channel pairs.
> Standard reco getter functions for correlation functions

- araproc/framework/dataset.py
This creates a dataset object that contains the excluded channels (according to the yaml file), plus the hpols or the vpols. This way if you want to compute a vpol only variable, you can do like:
```
snr_vpol = snr.get_snr(wavebundle, excluded_channels = d.excluded_channels_and_hpol)
```
> update excluded channel treatment

- araproc/analysis/standard_reco.py
Added calculation of full-phased (i.e. non-Hilbert enveloped) correlation function. This is cached for later use. Related functions were updated to support this. Added support for making non-Hilbert enveloped reconstruction maps.
> Cache full phased cross-correlation function

- araproc/framework/config_files/analysis_configs.yaml
here are the rf and soft trigger blocks for A1. config 1 runs are mostly all software triggers. therefore, the rf trigger block numbers are not necessary there and in this plot are simply copied from 2015-2016 run config for completeness.
[Full_Detector_Blocks_new.pdf](https://github.com/user-attachments/files/17548642/Full_Detector_Blocks_new.pdf)
> Updating A1 RF and Soft trigger readout blocks for all configs

- araproc/analysis/standard_reco.py
Timing table directories switch to temporary location at `/mnt/stashcache/icecube/PUBLIC/groups/arasoft/raytrace_timing_tables/Updated_Tables` while we wait for permanent location to be updated.
> Updated timing table directories to temporary location.

- araproc/analysis/standard_reco.py
For the CSW, for channels with a channel number greater than the reference channel, you need to multiply the time array of the cross correlation results by -1 so you're comparing the current channel's signal timing to the reference channel's timing, not vice versa. This is because AraRoot always calculated cross correlations by comparing lower numbered channels with respect to higher numbered channels. 
I accounted for this already when saving the fine-tuned arrival delay, but I neglected to consider this while using the reconstructed arrival time delays to fine tune the waveform shifting via cross correlation. So any CSW with a reference channel less than the number of total channels had a slightly odd CSW as a result. 
I ended up reformatting the handling of this to account for the sign …
> Fix Occasional Sign Error in CSW Fine Tuning 

- araproc/analysis/standard_reco.py
Calling full phase correlation was returning correlation SNR with values `>10**15` due to near zero values in leading and trailing samples. Fixed it by removing those. Here is an example of trimmed (now) vs previous correlation function.
> Fixing correlation SNR calculation

- araproc/framework/config_files/analysis_configs.yaml
- araproc/framework/dataset.py
SineSubtract was not correctly removing CW from spectra. The exact cause of this is unclear, but is apparently related to the fact that the waveforms were upsampled to 0.25 ns. I have changed the interpolation timestep back to 0.5 ns to fix this. 
For posterity, I include some information about what we found to be happening. SineSubtract failed to remove CW peaks, despite the fact that it would find these peaks and seem to fit them with an appropriate amplitude. The reason for the non-removal was that the calculated power reduction ratio would be very small or _negative_. In other words, subtraction somehow resulted in power being _added_ to the spectrum. CW removal was seen to be successful for 0.3 ns timestep as well, but there was some evidence that it may have been less effective as …
> Fixed CW removal

- araproc/analysis/standard_reco.py
- examples/run_example.py
Updated timing table paths to their permanent locations. Also update `run_example.py` to fix typo that was fixed in [PR#58](https://github.com/ara-software/AraProc/pull/58).
> Undo temporary timing table path fix

- araproc/framework/data_visualization.py
- araproc/framework/dataset.py
Added fast event index lookup for a requested event number. This is more efficient than a for loop to find the ROOT file index corresponding to a given event number. Also made spectrum plots y range dynamic.
Finally, added some functionality for if we ever want to check the station id that's stored in the ROOT data (stored as a class variable `data_station_id`. In the ended I decided not to use it, but I already coded this up and maybe it will be useful later. Can remove if wanted.
> Fast event idx lookup, dynamic spectrum range

- araproc/framework/data_visualization.py
`xvals` in plotting being set to frequency got dropped accidentally in [PR#60](https://github.com/ara-software/AraProc/pull/60). This fixes that.
> Fixed dropped frequency in plotting

- araproc/analysis/waveform_quality_cut.py
Added a module to perform quality checks on the waveform itself. To avoid errors during processing this needs to be separate from the daq quality check. Currently this just checks for waveform saturation, but wrote it so other checks can be easily added later.
> Add waveform quality check.

- araproc/framework/config_files/analysis_configs.yaml
Due to wrong RF block length setting (`rf_readout_limit: 26`) in A1 Config 1, more than 90% of RF and CP events were being flagged bad quality during L2 processing even if their waveform, although shorter, looked okay. That is because the actual length is 20 with time window size of 400 ns. I think, I will merge the change and reprocess Config 1 data. If there are questions/discussions, I will reopen the branch.
> Changing RF block length of A1 Config 1

- araproc/framework/dataset.py
This PR enables AraProc to give the user raw atri station events, to not have to load calibration data, which makes AraProc faster if all the user wants to do is e.g. count number of cal pulsers or software triggers, etc.
> Add ability to access raw atri station events

- araproc/__init__.py
Updated `__init__.py` to have different environmental variables to give the paths to the compiled AraSim and AraRoot libraries. New variables `ARA_ROOT_LIB_DIR` and `ARA_SIM_LIB_DIR` are meant to be descriptive and direct enough that unexpected directory structures can be accommodated without directly modifying `__init__.py`.
Users will need to add these variables to their environment for AraProc to work properly.
> Different AraSim and AraRoot path variables

- araproc/framework/data_visualization.py
Added a secondary axis for AraProc generated spectrum plots which shows the fractional power. This should help make it easier to efficiently set the minimum power ratio threshold for CW filters.
> Add fractional power axis

- araproc/framework/config_files/analysis_configs.yaml
- araproc/framework/data_visualization.py
- araproc/framework/map_utilities.py
A1 sees three most prominent CWs at 123, 224 and 403 MHz. I added three filters in narrow band to remove those (3 filters). Calibration seasons (and also sporadically in Polar winter) have frequencies in 147, 152, 275, 280, 475, 807 MHz. I clustered the other in 3 filters. Last one filter was added for entire bandwidth (50-950 MHz) to catch and remove any missed CWs. Shortening the list further is hard as the min_pow_ratio is hard to estimates for a larger bandwidth. In general, A1 being shallower, sees more CWs!
> A1 cw filters

- araproc/analysis/standard_reco.py
Changed the  get_corr_snr to check if index above threshold is empty. If yes, just return 0
> Fix get_corr_snr to handle empty corr. thresh cases

- araproc/framework/dataset.py
Redirecting output back to stdout and stderr was crashing for some reason. This should fix it. Not sure why it didn't always seem to break. 
Reference: [https://root-forum.cern.ch/t/how-to-invoke-gsystem-redirectoutput-0/14101](https://root-forum.cern.ch/t/how-to-invoke-gsystem-redirectoutput-0/14101)
> Fixed some ROOT nonsense.

- araproc/analysis/daq_quality_cut.py
It will now skip events with unknown trigger type.
> Quick fix on event quality issue ( if event has not known trigger type, tag as bad event)

- araproc/framework/data_visualization.py
Fixed a bug that was forcing the secondary y-axis (fraction power axis) ticks to go to 1, even if the primary y-axis range does not extend to the corresponding dBm value. This PR corrects this so that the y-axes correspond correctly and so the spectrum curve can be compared to either y-axis fairly.
> Fixed secondary spectrum axis bug

- araproc/framework/dataset.py
Old:
> Changed how SineSubtract determines which frequency has the peak power to simply use the global maximum (`GLOBALMAX` mode).
New: 
Changed how SineSubtract determines which frequency has the peak power to require that the peak be far enough over a baseline computed by a Savitzky Golay filter (`SAVGOLSUB` mode).
The rest of the discussion compares `NEIGHBORFACTOR` to `GLOBALMAX`. 
The default setting is `NEIGHBORFACTOR` which requires the candidate peak frequency to have an amplitude `1/0.15` times larger than either of its neighbors. If no candidate peak frequency satisfies this condition, the CW filtering terminates. This is a sort of safety measure to ensure it doesn't over subtract from the spectrum. However, in the case of ARA some CW features have enough width in the frequency …
> Update SineSubtract peak finding option

- araproc/analysis/impulsivity.py
Updated calculation of normalized CDF in terms of power rather than amplitude of sorted Hilbert envelope. This increases the separation in CDF related variables of signal and noise. The CDF thus changes from here
to here
> updated CDF calculation

- araproc/framework/dataset.py
Adds `cropped` waveform type, whose use case is mostly to separate D & R signals. The cropping parameters are passed by users through the `crop_times` argument, which just zeros out the trace outside the passed window. This waveform type is the last to be applied in the layers of waveform processing in dataset.
> Crop waveforms functions

- araproc/framework/dataset.py
Changed the run number for simulations from `-10` to the run number in the passed root file. This will help with analyzing simulations and finding bugs.
The parsing is pretty simple but should work based on how the AraSim generates output file names: https://github.com/ara-software/AraSim/blob/a10009706e1d9f256f7578d0eb98c9db6a9137d6/AraSim.cc#L198 (generally simulations we produce will always have `argc > 2` when running AraSim so that the run number is part of the file name)
> Added real run number for simulations

- araproc/analysis/cw_filter.py
- araproc/framework/dataset.py
- examples/run_example.py
This PR adds functionality for users to pass a pre-calculated ROOT file containing IDed CW for events in a run. 
When a file is passed, CW filters specified in `analysis_configs.yaml` are only applied to a given event & polarization if an identified CW frequency is in their filtering band, otherwise no filtering is applied (NB even if a filter does contain an identified frequency, the spectral amplitude in the band must still meet the minimum power ratio criteria for the filter to subtract anything).
If no file is passed, the default behaviour is to apply all CW filters as has been done previously.
Additional filter information is now tracked since this information does not have getter functions and the relevant variables are private in the `SineSubtract` class.
Some important limitations …
> Add support for filtering IDed CW

- araproc/analysis/hilbert.py
- araproc/analysis/rpr.py
- araproc/analysis/snr.py
This PR adds a sort-of jackknife estimate of the RMS of a trace and changes this to be the default RMS estimator in SNR calculations. The goal of this technique is both maximize the amount of the trace used to estimate the RMS and also be robust against impulsive signals in the trace. It does this by splitting the trace into segments and attempting to identify which segments are "outliers" in that they contain signal. It then calculates the RMS on all non-outlier segments in the trace. Segments are in terms of a fixed number of samples (to reduce sensitivity to the total trace length). By default 50 samples are used, corresponding to a 25 ns segment with our default 0.5 ns interpolation.
This new method has the advantage over our current estimate that it does not bias the RMS downwards …
> Jackknife RMS

- araproc/analysis/hilbert.py
This PR adds a calculation of the Hilbert envelope peak power divided by the rms in a portion of the envelope around the peak. This was developed on the PA CR search as an additional metric of the impulse-like nature of a trace that is less correlated with SNR. The current intent is to calculate this only for the CSW.
> Added hilbert peak over rms

- araproc/analysis/snr.py
- araproc/analysis/standard_reco.py
This PR makes changes in the `get_vpp` function for calculating peak-to-peak voltage. The changed function improves accuracy and flexibility by supporting both global and local extrema-based calculations. 
For a CP event
For a SPIce event
For an RF event (with signal)
For an RF event (with fluctuations)
> improved peak-to-peak calculation

- araproc/analysis/cw_filter.py
Added a check to make sure every IDed frequency has at least one filter applied. If it doesn't, it crashes and warns the user that it needs one.
> Added exception in case frequency has no filter

- araproc/analysis/fast_filter.py
- araproc/analysis/snr.py
This PR adds new analysis variables intended for use a low-cost rejection of the bulk of thermal events. These include an average spacetime interval and a (slightly modified/simplified) wavefront RMS.
> Added fast filter variables

- araproc/analysis/cw_filter.py
`if` statement to throw an error if no filter covering a flagged frequency is found was _inside_ the `for` loop over filters, which would cause a crash if the first filter checked did not cover that frequency. Fixed so that the check is done _after_ looping over all filters.
> Fixed if statement indent level.

- araproc/analysis/cw_filter.py
- araproc/framework/dataset.py
This PR adds a minimum CW ID frequency above which CW ID will be used to turn on filters. Below this frequency, all filters are turned on. (Ideally this would be removed someday.) The default is 120 MHz, which is what we used in our phase variance processing, but it can be adjusted by passing an argument when making the dataset object.
Also added two trace types: `cw_filtered` and `bandpassed` which only apply their respective filter.
> Add CW ID frequency threshold and trace types for cw filtering- and bandpassing-only

- araproc/framework/config_files/analysis_configs.yaml
Targeting 250, 300, 380, 407, 470, 500, and 950 MHz with the 2% power CW filter by looking in a window roughly +/- 20 MHz around each frequency. The rest of the frequency space is monitored with the 10% CW filter
> Make A2 CW filters full band with no overlap 

- araproc/analysis/cw_filter.py
- araproc/framework/dataset.py
This PR ensures CW filters are always applied in order of descending `min_power_ratio`. This was already enforced when CW ID is being used and previously was enforced by users via the ordering in yaml files when CW ID wasn't used. This update ensures the order that CW filters are applied is uniform.
Also added a getter function to have easier access to the flagged CW frequencies in each polarization of an event.
> Ensure CW filters are always sorted

- araproc/analysis/snr.py
Adjusted how we implemented the computationally-efficient version of the search for Vpp in a time window. This should now essentially never fail to calculate a Vpp.
> Fixed bug in windowed vpp

- araproc/analysis/cw_filter.py
- araproc/framework/dataset.py
This PR substantially reduces memory leaks due to CWID. These seem to originate from the way the TTree is read in and navigated, which somehow causes ROOT to allocate memory in the background. The TTreeReader avoids this. Remaining memory leaks might similarly be related to how TTrees are being read in.
Some changes we also introduced to the cw_filter module to avoid creating dictionaries of SineSubtract filters. I'm not sure if these were actually a problem, so we could revert that part of the code as the old version was a bit simpler in my opinion.
Also removed the previously added getter function `get_event_cw` as it's now redundant.
> CW ID leak fix

- araproc/framework/config_files/analysis_configs.yaml
Adjusted the expected readout lengths for A3 config 1 to the right values from data. These were set incorrectly due to this number being missing from most of the DAQ config logs that the scraping script pulls data from. The result was that essentially every event in the config was flagged as bad quality, even though there is nothing outwardly wrong with it. This fixes that error.
> Fixed expected readout lengths for A3 config 1

- araproc/framework/config_files/analysis_configs.yaml
This adds filters identified by dataset.get_cw_ids. There is also a filter added at 55 MHz, but it is kept weak enough that it does not eliminate the peaks there. Some example spectra are added here.
[A5_C1_2515_94198_unfiltered.pdf](https://github.com/user-attachments/files/20094446/A5_C1_2515_94198_unfiltered.pdf)
[A5_C1_2515_94198_filtered.pdf](https://github.com/user-attachments/files/20094447/A5_C1_2515_94198_filtered.pdf)
[A5_C1_2484_31093_unfiltered.pdf](https://github.com/user-attachments/files/20094451/A5_C1_2484_31093_unfiltered.pdf)
[A5_C1_2484_31093_filtered.pdf](https://github.com/user-attachments/files/20094452/A5_C1_2484_31093_filtered.pdf)
> Added and adjusted filters for A5.

- araproc/framework/config_files/analysis_configs.yaml
This PR makes some small adjustments to the A3 filters. There were some large ranges of identified CW frequencies (ex: 150-210) that I did not add a wide filter for because they did not produce skymaps and spectra that look like CW. Those events are also temporally clustered, so a ST cut should remove them.
> A3 filters

- araproc/framework/map_utilities.py
Add SPRESSO as an object to skymaps plotted for each event. Added SPRESSO to the default landmarks plotted.
> Add SPRESSO to plot_skymap

- araproc/analysis/dedisperse.py
- araproc/framework/data_visualization.py
This updates the dedisperser module. The idea here is that we want to pad the waveform with some buffer (in this case, 40 ns) before the dedispersion. This is necessary because the group delay of the system pushes the signal forward, so when it is removed, the signal shifts backwards in time. If we don't have any pre-padding, then the signal wraps around to the end of the trace, which is explicitly incorrect. We don't want to keep all of the pre-pad tho. So in this case, we pre-pad by 40 ns, and then keep 10 ns. The 10 ns is chosen by studying the largest group delay we see in the system response where the bandpass is still substantial. See the following plot.
> update the dedisperser with padding

- araproc/framework/dataset.py
I tried opening a file with "neutrino_only" in the filename and dataset.py couldn't parse it. Updated here.
> Allow dataset.py to process neutrino_only files

- araproc/framework/data_visualization.py
Add an argument to our `framework.data_visualization.plot_waveform_bundle()` function that lists a series of antennas to plot in a slightly grayed out color with the annotation "Masked to Analysis". For example if someone were to pass `excluded_channels=framework.dataset.AnalysisDataset.excluded_channels`, all channels masked to analysis would be plotted in greyed colors to help communicate to analyzers that the antennas did not contribute to analysis variable generation. Examples shown below: 
[station_2_run_18880_eventNo_47220_spectrum.pdf](https://github.com/user-attachments/files/22648500/station_2_run_18880_eventNo_47220_spectrum.pdf)
[station_2_run_18880_eventNo_47220_trace.pdf](https://github.com/user-attachments/files/22648505/station_2_run_18880_eventNo_47220_trace.pdf)
> Grey out masked channels
